// Tests the distribution generated by Java's Math.random() function.
public class TestRandom {
	public static void main(String[] args) {
		int times = Integer.parseInt(args[0]);
		int aboveHalf = 0;
		int belowHalf = 0;

		for (int i = 0; i < times; i++) {
			double rand = Math.random();
			if (rand > 0.5) {
				aboveHalf++;
			} else {
				belowHalf++;
			}
		}

		System.out.println("> 0.5: " + aboveHalf + " times");
		System.out.println("<= 0.5: " + belowHalf + " times");
		System.out.println("Ratio: "
				+  ((double) Math.min(belowHalf, aboveHalf) / Math.max(belowHalf, aboveHalf)));
	}
}
